apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: py-app
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: aumthakkar/2py-app
    backstage.io/techdocs-ref: dir:. # (<-- This one is for Techdocs) 
 
spec:
  type: service
  owner: development
  lifecycle: experimental