apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: aumthakkar/2py-app
 
spec:
  type: service
  owner: development
  lifecycle: experimental